version: '3.3'

services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "8000:80"
    links:
      - mongodb
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/app.access_log:/var/log/nginx/app.access_log
      - ./docker/nginx/log/app.error_log:/var/log/nginx/app.error_log

  redis:
    image: redis
    restart: on-failure

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test 
    # volumes:
    #   - ./docker/mongo/initdb.js:/docker-entrypoint-initdb.d/initdb.js

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 11112
    links:
      - mongodb
      - nginx
      - redis

