version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "8000:80"
    links:
      - mongodb
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/app.access_log:/var/log/nginx/app.access_log
      - ./docker/nginx/log/app.error_log:/var/log/nginx/app.error_log

  redis:
    container_name: redis
    image: redis
    restart: on-failure

  mongodb:
    container_name: mongo
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test 
    # volumes:
    #   - ./docker/mongo/initdb.js:/docker-entrypoint-initdb.d/initdb.js

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 11112
    links:
      - mongodb
      - nginx
      - redis
    environment:
      CHATADMIN_DB_HOST: mongodb
      CHATADMIN_DB_PASSWORD: admin
      CHATADMIN_DB_AUTH_SOURCE: admin
      CHATADMIN_REDIS_HOST: redis
